"""
Pydantic models for Orbital Nexus API requests and responses.

These schemas define the contract between frontend and backend.
Judges can read these to understand the data flow at a glance.
"""

from pydantic import BaseModel, Field


class UserQuery(BaseModel):
    """Incoming natural language query from the user."""

    query: str = Field(..., description="Natural language question from the user")
    lat: float = Field(default=28.4744, description="Latitude (default: Greater Noida)")
    lon: float = Field(
        default=77.5040, description="Longitude (default: Greater Noida)"
    )


class FusedDataSummary(BaseModel):
    """Summary of fused multi-satellite data for the queried region."""

    region: str = Field(..., description="Human-readable region name")
    lat: float = Field(default=28.4744, description="Query latitude")
    lon: float = Field(default=77.504, description="Query longitude")
    temperature_avg_c: float = Field(..., description="Average temperature (°C)")
    rainfall_mm: float = Field(..., description="Total rainfall (mm)")
    soil_moisture_pct: float = Field(..., description="Soil moisture (%)")
    ndvi_avg: float = Field(..., description="Average NDVI (0-1)")
    data_sources: list[str] = Field(..., description="List of satellite sources used")


class UIInstruction(BaseModel):
    """Instruction for the frontend to render a dashboard card."""

    card_type: str = Field(
        ...,
        description="Type: stat, chart, chart_line, chart_pie, list, alert, recommendation",
    )
    title: str = Field(..., description="Card heading")
    value: str = Field(..., description="Primary display value")
    subtitle: str = Field(default="", description="Secondary context text")
    color: str = Field(default="blue", description="Card accent color")
    data: dict | None = Field(
        default=None, description="Rich data payload for charts/lists"
    )


class LocationContext(BaseModel):
    """Fused location context from Open-Meteo + Bhuvan + Soil DB."""

    weather: dict = Field(
        ..., description="Live weather: temp, humidity, rain, moisture"
    )
    soil: dict = Field(..., description="Soil profile: type, ph, texture, nutrients")
    land_classification: str = Field(
        ..., description="ISRO Bhuvan land use classification"
    )
    region: str = Field(..., description="Human-readable region name")
    data_sources: list[str] = Field(..., description="Active data sources used")


class CropRecommendation(BaseModel):
    """AI-generated crop recommendation based on fused data."""

    crop_name: str = Field(..., description="Recommended crop")
    confidence: float = Field(..., description="Confidence score (0-1)")
    reasoning: str = Field(..., description="Why this crop is recommended")
    season: str = Field(..., description="Optimal planting season")


class QueryResponse(BaseModel):
    """Full response to a user query — sent back to the frontend."""

    intent: str = Field(
        ...,
        description="Parsed intent: crop_recommendation | weather_analysis | soil_check | flood_risk | general",
    )
    query_echo: str = Field(..., description="Original query echoed back")
    fused_data: FusedDataSummary = Field(
        ..., description="Fused satellite data summary"
    )
    guidance_text: str = Field(..., description="AI-generated guidance paragraph")
    ai_powered: bool = Field(default=False, description="Whether guidance was generated by Gemini AI")
    recommendations: list[CropRecommendation] = Field(
        default_factory=list, description="Crop recommendations (if applicable)"
    )
    ui_instructions: list[UIInstruction] = Field(
        ..., description="Cards for the frontend to render"
    )
